# Generated by Django 5.2.15 on 2026-07-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StripeWebhookSecret",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(blank=True, default=True)),
                (
                    "secret_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="A human-readable name for this secret.",
                        max_length=255,
                    ),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        help_text="The secret provided by Stripe.",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StripeWebhookSecretRoute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "url_name",
                    models.CharField(
                        help_text="The url_name for the route", max_length=255
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="payment_gateway.stripewebhooksecret",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
