# Generated by Django 5.2.15 on 2026-07-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment_gateway", "0001_add_webhook_secret_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripewebhooksecret",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="stripewebhooksecretroute",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
