# Generated by Django 4.2.16 on 2025-03-04 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_scim_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
