# Generated by Django 5.1.7 on 2025-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_add_global_id_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="global_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The SSO ID (usually a Keycloak UUID) for the user.",
                max_length=36,
            ),
        ),
    ]
