language: python

cache: pip

python:
  - 3.6
  - 3.7
  - 3.8

# to add a new module, just add another entry here
env:
  - NAME=mitol-django-mail

before_install:
  - pip install poetry codecov
  - cd $NAME

install: poetry install
script:
  - poetry run black --check .
  - poetry run isort -c
  - poetry run pytest
  - poetry run mypy --show-error-codes mitol/

after_success:
  - TRAVIS_BUILD_DIR=$PWD
  - coverage xml
  - codecov
#
# jobs:
#   include:
#     - stage: PyPI Release
#       python: 3.8
#       before_deploy:
#         - cd $NAME
#         - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
#         - poetry build
#       deploy:
#         provider: script
#         script: poetry publish
#         on:
#           tags: true
