---
services:

  db:
    image: postgres@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    environment:
      POSTGRES_DB: ol_django
      POSTGRES_PASSWORD: postgres
    ports:
    - "${POSTGRES_PORT:-55432}:5432"

  redis:
    image: redis@sha256:c88d347edef6249a6d2293f926f1eeb48bd40c57cbcd02c07f52e7f1fd2cb46b
    ports:
    - "${REDIS_PORT:-36379}:6379"

  shell:
    build:
      target: uv
    volumes:
    - .:/home/dev/src
    - cache:/home/dev/.cache/
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
    - db

volumes:
  cache:
