---
services:

  db:
    image: postgres@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    environment:
      POSTGRES_DB: ol_django
      POSTGRES_PASSWORD: postgres
    ports:
    - "${POSTGRES_PORT:-55432}:5432"

  redis:
    image: redis@sha256:c88d347edef6249a6d2293f926f1eeb48bd40c57cbcd02c07f52e7f1fd2cb46b
    ports:
    - "${REDIS_PORT:-36379}:6379"

  shell:
    build:
      target: uv
    volumes:
    - .:/home/dev/src
    - cache:/home/dev/.cache/
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
    - db

volumes:
  cache:
