---
services:

  db:
    image: postgres@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    environment:
      POSTGRES_DB: ol_django
      POSTGRES_PASSWORD: postgres
    ports:
    - "${POSTGRES_PORT:-55432}:5432"

  redis:
    image: redis@sha256:832d7785830f3f4b559300e6191fc914b15642c1935252338825cf4332200148
    ports:
    - "${REDIS_PORT:-36379}:6379"

  shell:
    build:
      target: uv
    volumes:
    - .:/home/dev/src
    - cache:/home/dev/.cache/
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
    - db

  release:
    build:
      target: release
    volumes:
    - cache:/home/dev/.cache/
    - ./ssh:/home/dev/.ssh:ro
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    depends_on:
    - db

volumes:
  cache:
