[GLOBAL]
pants_version = "2.14.0"
pants_ignore.remove = [
  # this is gitignored, which pants pulls in, so we need to un-ignore it
  "testapp/settings/dev.py",
]
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
  'pants.backend.python',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.lint.isort',
  'pants.backend.python.lint.black',
  'pants.backend.python.typecheck.mypy',
  # custom pants plugins
  'python_distribution',
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  "src",
  "tests",
  "/build-support/bin",
  "/pants-plugins",
]

[test]
extra_env_vars = [
  "DJANGO_SETTINGS_MODULE=testapp.settings.test"
]

[repl]
shell = "ipython"

[ipython]
version = "ipython==7.23.1"
lockfile = "build-support/ipython.lockfile"

[python]
interpreter_constraints = ['>=3.7']
enable_resolves = true

[python.resolves]
python-default = "build-support/python-default.lock" 


[setup-py-generation]
first_party_dependency_version_scheme = "compatible"

[black]
version = "black==22.12.0"
lockfile = "build-support/black.lockfile"

[mypy]
version = "mypy==0.991"
lockfile = "build-support/mypy.lockfile"
extra_requirements = [
  "django-stubs==1.13.1",
  "djangorestframework-stubs[compatible-mypy]==1.8.0"
]

[flake8]
version = "flake8>=5.0.0,<6"
lockfile = "build-support/flake8.lockfile"

[pytest]
lockfile = "build-support/pytest.lockfile"
args = [
  "--cov .",
  "--cov-report term ",
  "--cov-report html",
  "--cov-report xml",
  "--reuse-db"
]
execution_slot_var = "PANTS_EXECUTION_SLOT"
extra_requirements.add = [
  "pytest-django==3.10.0",
  "pytest-mock==1.10.1",
  "ipdb"
]

[isort]
version = "isort==5.8.0"
lockfile = "build-support/isort.lockfile"
args = [
  "--profile=black",
  "--project=mitol",
  "-m=3",
]
