[GLOBAL]
pants_version = "2.6.0.dev0"
pants_ignore.remove = [
  # this is gitignored, which pants puls in, so we need to un-ignore it
  "testapp/settings/dev.py",
]
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
  'pants.backend.python',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.lint.isort',
  'pants.backend.python.lint.black',
  'pants.backend.python.typecheck.mypy',
  # custom pants plugins
  'django_run',
  'python_distribution',
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  "src",
  "tests",
  "/build-support/bin",
  "/pants-plugins",
]

[test]
extra_env_vars = [
  "DJANGO_SETTINGS_MODULE=testapp.settings.test"
]

[repl]
shell = "ipython"

[ipython]
version = "ipython==7.23.1"

[python-setup]
interpreter_constraints = ['>=3.7']
requirement_constraints = "requirements.txt"

[setup-py-generation]
first_party_dependency_version_scheme = "compatible"

[black]
version = "black==21.5b1"

[mypy]
version = "mypy==0.782"
extra_requirements = [
  "django-stubs==1.6.0",
  "djangorestframework-stubs==1.2.0"
]

[flake8]
version = "flake8==3.8.0"

[pytest]
# config = "build-support/pytest.ini"
args = [
  "--cov .",
  "--cov-report term ",
  "--cov-report html",
  "--cov-report xml",
  "--reuse-db"
]
execution_slot_var = "PANTS_EXECUTION_SLOT"
pytest_plugins.add = [
  "pytest-django==3.10.0",
  "pytest-mock==1.10.1",
  "ipdb"
]

[isort]
version = "isort==5.8.0"
args = [
  "--profile=black",
  "--project=mitol",
  "-m=3",
]
