[GLOBAL]
pants_version = "2.15.0rc5"
pants_ignore.remove = [
  # this is gitignored, which pants pulls in, so we need to un-ignore it
  "testapp/settings/dev.py",
]
pythonpath = [
  "%(buildroot)s/pants-plugins"
]
backend_packages = [
  'pants.backend.python',
  'pants.backend.python.lint.flake8',
  'pants.backend.python.lint.isort',
  'pants.backend.python.lint.black',
  'pants.backend.python.typecheck.mypy',
  # custom pants plugins
  'python_distribution',
]

# NOTE: this is a workaround for an upstream bug in the version of pex used in pants<2.16.x
[pex-cli]
version = "v2.1.123"
known_versions = [
    "v2.1.123|linux_arm64|3a2cba02946eb8859393906673bb56ecf6ebee72961bc8f3ca1ae754493733c6|4076395",
    "v2.1.123|linux_x86_64|3a2cba02946eb8859393906673bb56ecf6ebee72961bc8f3ca1ae754493733c6|4076395",
    "v2.1.123|macos_arm64|3a2cba02946eb8859393906673bb56ecf6ebee72961bc8f3ca1ae754493733c6|4076395",
    "v2.1.123|macos_x86_64|3a2cba02946eb8859393906673bb56ecf6ebee72961bc8f3ca1ae754493733c6|4076395",
]

[cli.alias]
ol-project = "run build-support/bin:ol-project --"

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  "src",
  "tests",
  "/build-support/bin",
  "/pants-plugins",
]

[test]
extra_env_vars = [
  "DATABASE_URL",
  "DJANGO_SETTINGS_MODULE=testapp.settings.test",
]

[repl]
shell = "ipython"

[ipython]
version = "ipython==7.23.1"
lockfile = "build-support/lockfiles/ipython.lockfile"

[python]
interpreter_constraints = ['>=3.8']
enable_resolves = true

[python.resolves]
python-default = "build-support/lockfiles/python-default.lockfile" 

[setup-py-generation]
first_party_dependency_version_scheme = "any"

[black]
version = "black==22.12.0"
lockfile = "build-support/lockfiles/black.lockfile"

[mypy]
version = "mypy==0.991"
lockfile = "build-support/lockfiles/mypy.lockfile"
extra_requirements = [
  "django-stubs==1.13.1",
  "djangorestframework-stubs[compatible-mypy]==1.8.0"
]

[flake8]
version = "flake8>=5.0.0,<6"
lockfile = "build-support/lockfiles/flake8.lockfile"

[pytest]
lockfile = "build-support/lockfiles/pytest.lockfile"
args = [
  "--cov .",
  "--cov-report term ",
  "--cov-report html",
  "--cov-report xml",
  "--reuse-db"
]
extra_requirements.add = [
  "pytest-django==3.10.0",
  "pytest-mock==1.10.1",
  "ipdb"
]
execution_slot_var = "PANTS_EXECUTION_SLOT"

[isort]
version = "isort==5.8.0"
lockfile = "build-support/lockfiles/isort.lockfile"
args = [
  "--profile=black",
  "--project=mitol",
  "-m=3",
]
