[GLOBAL]
pants_version = "2.21.0"
pants_ignore.remove = [
  # this is gitignored, which pants pulls in, so we need to un-ignore it
  "testapp/settings/dev.py",
]
pythonpath = [
  "%(buildroot)s/pants-plugins"
]
backend_packages = [
  'pants.backend.python',
  'pants.backend.experimental.python.lint.ruff.check',
  'pants.backend.experimental.python.lint.ruff.format',
  'pants.backend.python.typecheck.mypy',
  # custom pants plugins
  'python_distribution',
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  "src",
  "tests",
  "/build-support/bin",
  "/pants-plugins",
]

[test]
extra_env_vars = [
  "DATABASE_URL",
  "DJANGO_SETTINGS_MODULE=testapp.settings.test",
]

[repl]
shell = "ipython"

# [ipython]
# version = "ipython==7.23.1"
# lockfile = "build-support/lockfiles/ipython.lockfile"

[python]
interpreter_constraints = ['>=3.8']
enable_resolves = true

[python.resolves]
python-default = "build-support/lockfiles/python-default.lockfile" 

[setup-py-generation]
first_party_dependency_version_scheme = "any"

[mypy]
requirements = [
  "django-stubs==1.13.1",
  "djangorestframework-stubs[compatible-mypy]==1.8.0"
]

[pytest]
args = [
  "--cov .",
  "--cov-report term ",
  "--cov-report html",
  "--cov-report xml",
  "--reuse-db"
]
requirements.add = [
  "pytest-django==3.10.0",
  "pytest-mock==1.10.1",
  "ipdb"
]
execution_slot_var = "PANTS_EXECUTION_SLOT"

[ruff]
args = [
  "--fix"
]