# Generated by Django 5.2.15 on 2026-06-30 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_auditabletestmodel_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstlevel2",
            name="second_levels",
        ),
        migrations.DeleteModel(
            name="FirstLevel1",
        ),
        migrations.DeleteModel(
            name="SecondLevel1",
        ),
        migrations.DeleteModel(
            name="FirstLevel2",
        ),
        migrations.DeleteModel(
            name="SecondLevel2",
        ),
    ]
