"""
API for the Payment Gateway
"""

import abc
import hashlib
import hmac
import json
import logging
import uuid
import warnings
from base64 import b64encode
from dataclasses import asdict
from decimal import Decimal
from functools import wraps

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=SyntaxWarning)
    from CyberSource import (
        CreateSearchRequest,
        Ptsv2paymentsClientReferenceInformation,
        Ptsv2paymentsidcapturesOrderInformationAmountDetails,
        Ptsv2paymentsidrefundsOrderInformation,
        RefundApi,
        RefundPaymentRequest,
        SearchTransactionsApi,
        TransactionDetailsApi,
    )
import stripe
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.http import HttpRequest
from mitol.common.utils.datetime import now_in_utc
from mitol.payment_gateway import constants
from mitol.payment_gateway.dataclasses import (
    CartItem,
    LookupCartItem,
    Order,
    ProcessorResponse,
    Refund,
    StripeCheckoutSessionStatus,
)
from mitol.payment_gateway.exceptions import (
    BadStripeWebhookSecretError,
    ImproperCartItemError,
    ImproperStripeWebhookRequestError,
    InvalidStripeCheckoutSessionError,
    InvalidTransactionException,
    NoStripeWebhookSecretError,
    RefundDuplicateException,
)
from mitol.payment_gateway.models import StripeWebhookSecret
from mitol.payment_gateway.payment_utils import (
    clean_request_data,
    quantize_decimal,
    strip_nones,
)
from stripe.checkout import Session as StripeCheckoutSession

log = logging.getLogger(__name__)


class PaymentGateway(abc.ABC):
    """
    PaymentGateway provides a standardized interface to payment processors.
    This is designed to work with processors that have a hosted checkout-type
    product (i.e. you assemble a payload for the processor, do some sort of
    processing to make that suitable for them, and then redirect the customer to
    the processor to capture card information).
    """

    _GATEWAYS = {}

    def __init_subclass__(cls, *, gateway_class, **kwargs):
        super().__init_subclass__()

        if gateway_class in cls._GATEWAYS:
            raise TypeError(f"{gateway_class} has already been defined")  # noqa: EM102, TRY003

        cls._GATEWAYS[gateway_class] = cls

    def find_gateway_class(func):  # noqa: N805
        @wraps(func)
        def _find_gateway_class(cls, payment_type, *args, **kwargs):
            if payment_type not in cls._GATEWAYS:
                return TypeError(f"{payment_type} not defined")

            return func(cls, cls._GATEWAYS[payment_type](), *args, **kwargs)

        return _find_gateway_class

    @abc.abstractmethod
    def prepare_checkout(
        self, order, receipt_url, cancel_url, backoffice_post_url, **kwargs
    ):
        """
        This is the entrypoint to the payment gateway.
        Args:
            order: Order object (see the dataclasses above)
            receipt_url: redirect URL used by the processor when the transaction is successful
            cancel_url: redirect URL used by the processor when the transaction has been cancelled
        Keyword Args:
            merchant_fields: list containing any additional data for the transaction
        Returns:
            dictionary:
                - url: URL to the workflow on the payment processor
                - payload: payload to send to the payment processor
                - method: HTTP method to use

        Total price will be calculated as quantity * unitprice. This is the only
        calculation the gateway does (or should do) - coupons and discounts
        should be handled before starting this process.

        The merchant_fields argument is processor dependent. A given payment
        processor may not have a facility to store arbitrary data with the
        transaction. CyberSource specifically has up to 100 definable
        merchant_defined_fields that can be specified - xPro uses this, and
        that's what this is for. This should just be a standard array - the
        class that handles this should format the data as needed for the
        processor in question (or ignore it entirely).
        """  # noqa: E501, D401

    @staticmethod
    @abc.abstractmethod
    def get_refund_request(transaction_dict: dict):
        """
        This is the entrypoint to the payment gateway for creating refund request objects.
        Args:
            transaction_dict (Dict): Data dictionary of the payment transaction response of the Gateway
        Returns:
            Object (Refund): Refund An object of Refund class that can be used for Refund operations

        """  # noqa: E501, D401

    @abc.abstractmethod
    def perform_processor_response_validation(self, request):
        """
        Validates a response generated by the payment processor. This is meant
        to be used in an authentication class.

        Args:
            request:    HttpRequest object or equivalent (DRF Request)

        Returns:
            True or False
        """  # noqa: D401

    @abc.abstractmethod
    def decode_processor_response(self, request):
        """
        Decodes the post-completion response from the payment processor
        and converts it to a generic representation of the data.

        Args:
            request:    HttpRequest object or equivalent (DRF Request)

        Returns:
            ProcessorResponse
        """  # noqa: D401

    @staticmethod
    @abc.abstractmethod
    def get_client_configuration():
        """
        This is the function that will provide required configuration for a PaymentGateway
        """  # noqa: E501, D401

    @abc.abstractmethod
    def perform_refund(self, refund):
        """
        This is the entrypoint to the payment gateway.

        Args:
            refund: (Refund) Data class for refund request (see the data classes above)
        Returns:
            ProcessorResponse

        """  # noqa: D401

    @classmethod
    @find_gateway_class
    def start_payment(
        cls,
        payment_type,
        order: Order,
        receipt_url: str,
        cancel_url: str,
        backoffice_post_url: str | None = None,
        **kwargs,
    ):
        """
        Starts the payment process for the given type. See prepare_checkout for
        more detail about these arguments (other than payment_type).

        Args:
            payment_type    String; gateway class to use
            order           Dict; order information
            cart            List; cart items
            receipt_url     String; success redirect URL target
            cancel_url      String; cancel redirect URL target
        Keyword Args:
            merchant_fields List; additional info for processor
        Returns:
            see prepare_checkout
        """  # noqa: D401

        return payment_type.prepare_checkout(
            order, receipt_url, cancel_url, backoffice_post_url, **kwargs
        )

    @classmethod
    @find_gateway_class
    def create_refund_request(cls, payment_type, transaction_dict: dict):
        """
        Iterate through the given payment transaction dictionary and returns a refund object to perform operations on.
        Args:
            payment_type (String): gateway class to use
            transaction_dict (Dict): Dictionary of the data acquired through a successful Gateway payment
        Returns:
            see get_refund_request
        """  # noqa: E501

        return payment_type.get_refund_request(transaction_dict)

    @classmethod
    @find_gateway_class
    def start_refund(cls, payment_type, refund: Refund):
        """
        Starts the payment refund process for the given type. See prepare_checkout for
        more detail about these arguments (other than payment_type).

        Args:
            payment_type    String; gateway class to use
            refund          Object: Refund
        Returns:
            see perform_refund
        """  # noqa: D401

        return payment_type.perform_refund(refund)

    @classmethod
    @find_gateway_class
    def validate_processor_response(cls, payment_type, request):
        """
        Kicks off validation of a processor response.

        Args:
            payment_type:   String; gateway class to use
            request:        HttpRequest object or equivalent

        Returns:
            True or False (this is implementation-specific)
        """

        return payment_type.perform_processor_response_validation(request)

    @classmethod
    @find_gateway_class
    def get_formatted_response(cls, payment_type, request):
        """
        Runs the request through the processor response decoder.

        Args:
            payment_type:   String; gateway class to use
            request:        HttpRequest object or equivalent

        Returns:
            ProcessorResponse
        """  # noqa: D401

        return payment_type.decode_processor_response(request)

    @classmethod
    @find_gateway_class
    def get_gateway_class(cls, payment_type):
        """
        Just returns the resolved payment gateway class.
        """
        return payment_type


class CyberSourcePaymentGateway(
    PaymentGateway, gateway_class=constants.MITOL_PAYMENT_GATEWAY_CYBERSOURCE
):
    """
    The CyberSource implementation of Payment Gateway. This provides the data
    manipulation and signing necessary to pass transactions to CyberSource via
    their Secure Acceptance Hosted Checkout product.

    Documentation about this: https://developer.cybersource.com/library/documentation/dev_guides/Secure_Acceptance_Hosted_Checkout/html/index.html#t=Topics%2Fcover_ENT.htm
    """

    def _generate_line_items(self, cart):
        """
        Generates CyberSource-formatted line items based on what's in the cart.

        The unit price being stored should be the unit price after any discounts
        have been applied. The tax amount should be the _total_ for the line.

        Args:
            cart:   List of CartItems

        Retuns:
            Tuple: formatted lines and the total cart value
        """  # noqa: D401
        lines = {}
        cart_total = 0
        tax_total = 0

        for i, line in enumerate(cart):
            cart_total += line.quantity * line.unitprice
            tax_total += line.taxable

            lines[f"item_{i}_code"] = str(line.code)
            lines[f"item_{i}_name"] = str(line.name)[:254]
            lines[f"item_{i}_quantity"] = line.quantity
            lines[f"item_{i}_sku"] = line.sku
            lines[f"item_{i}_tax_amount"] = str(line.taxable)
            lines[f"item_{i}_unit_price"] = str(line.unitprice)

        return (lines, cart_total, tax_total)

    def _generate_cybersource_sa_signature(self, payload):
        """
        Generate an HMAC SHA256 signature for the CyberSource Secure Acceptance payload
        Args:
            payload:    Dict; the payload to be sent to CyberSource
        Returns:
            str: The signature
        """

        keys = payload["signed_field_names"].split(",")
        message = ",".join(f"{key}={payload[key]}" for key in keys)

        digest = hmac.new(
            settings.MITOL_PAYMENT_GATEWAY_CYBERSOURCE_SECURITY_KEY.encode("utf-8"),
            msg=message.encode("utf-8"),
            digestmod=hashlib.sha256,
        ).digest()

        return b64encode(digest).decode("utf-8")

    def _sign_cybersource_payload(self, payload):
        """
        Return a payload signed with the CyberSource key

        Args:
            payload: Dict; an unsigned payload to be sent to CyberSource

        Returns:
            dict: A signed payload to be sent to CyberSource
        """
        field_names = sorted(list(payload.keys()) + ["signed_field_names"])  # noqa: RUF005
        payload = {**payload, "signed_field_names": ",".join(field_names)}
        return {
            **payload,
            "signature": self._generate_cybersource_sa_signature(payload),
        }

    def prepare_checkout(
        self,
        order: Order,
        receipt_url: str,
        cancel_url: str,
        backoffice_post_url: str | None = None,
        **kwargs,
    ):
        """
        This acts more as a coordinator for the internal methods in the class.

        The username attached to the order is passed to CyberSource. However, it
        won't accept an email address-like username (see
        https://github.com/mitodl/mitxonline/issues/593), so this generates a
        sha256 hash of the username to pass in to CyberSource. This hash isn't
        stored anywhere.
        """  # noqa: D401

        (line_items, total, tax_total) = self._generate_line_items(order.items)

        formatted_merchant_fields = {}

        if "merchant_fields" in kwargs and kwargs["merchant_fields"] is not None:
            for idx, field_data in enumerate(kwargs["merchant_fields"], start=1):
                # CyberSource maxes out at 100 of these
                # there should really only ever be 6 at most (for xPro)
                if idx > 100:  # noqa: PLR2004
                    break

                formatted_merchant_fields[f"merchant_defined_data{idx}"] = field_data

        consumer_id = hashlib.sha256(order.username.encode("utf-8")).hexdigest()

        payload = {
            "access_key": settings.MITOL_PAYMENT_GATEWAY_CYBERSOURCE_ACCESS_KEY,
            "amount": str(quantize_decimal(total + tax_total)),
            "tax_amount": str(quantize_decimal(tax_total)),
            "consumer_id": consumer_id,
            "currency": "USD",
            "locale": "en-us",
            **line_items,
            "line_item_count": len(order.items),
            **formatted_merchant_fields,
            "reference_number": order.reference,
            "profile_id": settings.MITOL_PAYMENT_GATEWAY_CYBERSOURCE_PROFILE_ID,
            "signed_date_time": now_in_utc().strftime(constants.ISO_8601_FORMAT),
            "override_custom_receipt_page": receipt_url,
            "override_custom_cancel_page": cancel_url,
            "transaction_type": "sale",
            "transaction_uuid": uuid.uuid4().hex,
            "unsigned_field_names": "",
            "customer_ip_address": order.ip_address if order.ip_address else None,
        }
        if backoffice_post_url:
            payload["override_backoffice_post_url"] = backoffice_post_url

        signed_payload = self._sign_cybersource_payload(payload)

        return {
            "payload": signed_payload,
            "url": settings.MITOL_PAYMENT_GATEWAY_CYBERSOURCE_SECURE_ACCEPTANCE_URL,
            "method": "POST",
        }

    @staticmethod
    def get_client_configuration():
        """
        Get the configuration required for CyberSource API client
        """
        configuration_dictionary = {
            "authentication_type": "http_signature",
            "merchantid": settings.MITOL_PAYMENT_GATEWAY_CYBERSOURCE_MERCHANT_ID,
            "run_environment": settings.MITOL_PAYMENT_GATEWAY_CYBERSOURCE_REST_API_ENVIRONMENT,  # noqa: E501
            "merchant_keyid": settings.MITOL_PAYMENT_GATEWAY_CYBERSOURCE_MERCHANT_SECRET_KEY_ID,  # noqa: E501
            "merchant_secretkey": settings.MITOL_PAYMENT_GATEWAY_CYBERSOURCE_MERCHANT_SECRET,  # noqa: E501
            "timeout": 1000,
        }
        return configuration_dictionary  # noqa: RET504

    @staticmethod
    def get_refund_request(transaction_dict: dict):
        """
        Create a refund request object to from the required attributes in the payment dictionary
        Args:
            transaction_dict: (Dict) Data dictionary of the payment response of the Gateway
            Ideally, The transaction dictionary should have transaction_id, req_amount, req_currency in case of
            CyberSource.
        Returns:
            Object: Refund An object of Refund class that can be used to operate the Refunds

        """  # noqa: E501
        try:
            # If a required value exists we can't decide if it's valid so let the API throw that error itself  # noqa: E501
            transaction_id = transaction_dict["transaction_id"]
            order_amount = transaction_dict["req_amount"]
            order_currency = transaction_dict["req_currency"]

            return Refund(
                transaction_id=transaction_id,
                refund_amount=order_amount,
                refund_currency=order_currency,
            )
        except KeyError as error:
            raise InvalidTransactionException() from error  # noqa: RSE102

    def perform_refund(self, refund):
        """
        Based on the provided refund detail data object, this method calls the cyber source refund API call after
        performing the appropriate operation on the data.

        returns:
            i) API Success:
                Returns a ProcessorResponse object that the caller app can use to perform whatever they need

            ii)  API Failure ("DUPLICATE_REQUEST"):
                Raises RefundDuplicateException when the refund API call is duplicate

            iii)  API Failure (General):
                Raises the exception(Mostly CyberSource.rest.ApiException) to the caller to decide what their
                application behaviour
        """  # noqa: E501

        api_instance = RefundApi(self.get_client_configuration())
        refund_payload = self.generate_refund_payload(refund)
        transaction_id = refund.transaction_id

        try:
            _return_data, _status, body = api_instance.refund_payment(
                refund_payload, transaction_id
            )
            response_body = json.loads(body)

            # Transforming the response in a format that process response decoder can work on while keeping our  # noqa: E501
            # structure consistent
            response_transformed = {
                "data": response_body,
                "reason_code": response_body.get("processorInformation", {}).get(
                    "responseCode", ""
                ),
                "transaction_id": transaction_id,
                "message": "The refund request was successful",
                "decision": response_body["status"],
            }

            response = self.decode_processor_api_response(response_transformed)
            return response  # noqa: RET504, TRY300

        except Exception as ex:
            # Some error responses (e.g. 401 Unauthorized) use a different body
            # schema that does not contain a top-level "reason" key.  Guard
            # against missing attributes/keys so we always re-raise a useful
            # exception rather than masking the original error with a KeyError.
            exception_body = None
            if hasattr(ex, "body") and ex.body:
                try:
                    exception_body = json.loads(ex.body)
                except (ValueError, TypeError):
                    pass

            # Special case for request failure when DUPLICATE_REQUEST
            if exception_body and exception_body.get("reason") == ProcessorResponse.STATE_DUPLICATE:
                raise RefundDuplicateException(  # noqa: B904
                    exception_body["reason"],
                    transaction_id,
                    refund.refund_amount,
                    exception_body,
                    message=exception_body["message"],
                )

            raise ex  # noqa: TRY201

    def generate_refund_payload(self, refund):
        """
        CyberSource API client would expect the payload in a specific format to perform the refund API call.
        This method generated that payload out of the Refund data class(s)
        """  # noqa: E501
        transaction_id = refund.transaction_id
        order_information_amount_details = (
            Ptsv2paymentsidcapturesOrderInformationAmountDetails(
                total_amount=refund.refund_amount, currency=refund.refund_currency
            )
        )

        order_information = Ptsv2paymentsidrefundsOrderInformation(
            amount_details=clean_request_data(order_information_amount_details.__dict__)
        )
        client_reference_information = Ptsv2paymentsClientReferenceInformation(
            transaction_id=transaction_id
        )
        refund_request = RefundPaymentRequest(
            client_reference_information=clean_request_data(
                client_reference_information.__dict__
            ),
            order_information=clean_request_data(order_information.__dict__),
        )
        refund_request = refund_request.__dict__

        return json.dumps(refund_request)

    def perform_processor_response_validation(self, request):
        """
        CyberSource will send back a payload signed in the same manner that the
        original transaction was sent, so we just reuse that process here, with
        some logic to pull the proper request data out depending on HTTP verb.
        """
        if request.method == "POST":
            passed_payload = getattr(request, "data", getattr(request, "POST", {}))
        else:
            passed_payload = getattr(
                request, "query_params", getattr(request, "GET", {})
            )

        signature = self._generate_cybersource_sa_signature(passed_payload)

        return passed_payload["signature"] == signature

    def convert_to_order(self, response):
        """
        CyberSource includes the order in its response, using the same
        field names prepended with "req_". This will grab those fields
        out of the response and convert it back to an Order and a set of
        CartItems. (Not all payment processor APIs may support this, so this
        is just defined for the CyberSource one.)

        Note that the username that is returned by CyberSource will be the
        sha256 hash of the username that was originally passed in, and *not* the
        actual username.

        Args:
            response: Dict; the data from the response

        Returns:
            Order
        """
        items = []

        for i in range(int(response["req_line_item_count"])):
            line = CartItem(
                code=response[f"req_item_{i}_code"],
                name=response[f"req_item_{i}_name"],
                sku=response[f"req_item_{i}_sku"],
                unitprice=response[f"req_item_{i}_unit_price"],
                taxable=response[f"req_item_{i}_tax_amount"],
                quantity=response[f"req_item_{i}_quantity"],
            )
            items.append(line)

        order = Order(
            username=response["req_consumer_id"],
            ip_address=response["req_customer_ip_address"],
            reference=response["req_reference_number"],
            items=items,
        )

        return order  # noqa: RET504

    def decode_processor_response(self, request):
        """
        The CyberSource implementation of this. The ProcessorResponse
        class was designed around this processor so the state codes map
        one-to-one to the decision field that gets passed back from them.

        The reason code and transaction ID fields don't appear in certain
        states.
        """  # noqa: D401
        if request.method == "POST":
            response = getattr(request, "data", getattr(request, "POST", {}))
        else:
            response = getattr(request, "query_params", getattr(request, "GET", {}))

        fmt_response = ProcessorResponse(
            ProcessorResponse.STATE_ERROR,
            "Could not decode the processor response",
            "",
            "",
            "",
        )

        # Format the order response using quick wrapping functions
        fmt_response.message = self._get_response_message(response)
        fmt_response.response_code = self._get_reason_code(response)
        fmt_response.transaction_id = self._get_response_transaction_id(response)
        fmt_response.state = self._get_decision_from_response(response)

        return fmt_response

    def decode_processor_api_response(self, response):
        """
        The CyberSource implementation for decoding the processor response specifically for the API calls. The response
        from the SecureAccept and the REST API calls is different so like "decode_processor_response"
        this method generates the common ProcessorResponse out of the API response
        """  # noqa: E501, D401

        fmt_response = ProcessorResponse(
            ProcessorResponse.STATE_ERROR,
            "Could not decode the processor response",
            "",
            "",
            "",
        )
        fmt_response.message = self._get_response_message(response)

        # CyberSource has no reason codes for cancellation at least
        fmt_response.response_code = self._get_reason_code(response)

        # Same for transaction_id
        fmt_response.transaction_id = self._get_response_transaction_id(response)

        fmt_response.state = self._get_decision_from_response(response)
        fmt_response.response_data = response.get("data", "")

        return fmt_response

    def _get_response_message(self, response):
        """Getter for message key from payload"""
        return response.get("message", "")

    def _get_reason_code(self, response):
        """Getter for reason_code key from payload"""
        return response.get("reason_code", "")

    def _get_response_transaction_id(self, response):
        """Getter for transaction_id key from payload"""
        return response.get("transaction_id", "")

    def _get_decision_from_response(self, response):  # noqa: PLR0911
        """Getter for appropriate response state based on the decision key from payload"""  # noqa: E501
        decision = response.get("decision", None)

        if not decision or decision == "ERROR":
            return ProcessorResponse.STATE_ERROR
        elif decision == "ACCEPT":
            return ProcessorResponse.STATE_ACCEPTED
        elif decision == "DECLINE":
            return ProcessorResponse.STATE_DECLINED
            # maybe should log here? this is a straight-up something went wrong between the app and the processor state  # noqa: E501
        elif decision == "CANCEL":
            return ProcessorResponse.STATE_CANCELLED
        elif decision == "REVIEW":
            return ProcessorResponse.STATE_REVIEW
        elif decision == "PENDING":
            return ProcessorResponse.STATE_PENDING

        return ProcessorResponse.STATE_ERROR

    def find_transactions(self, reference_numbers: list[str], limit=20):
        """
        Performs a search for the transactions specified. For simplicity, this
        assumes the data set specified is reference numbers. If your system doesn't
        produce unique reference numbers (or if they get reused for whatever reason),
        this will likely return multiple transactions for the same order ID.

        Args:
        - reference_numbers (list of strings): List of reference numbers to look for
        - limit (int): Max number of rows to return (defaults to 20)

        Returns:
        - List of CyberSource transaction IDs

        Raises:
        - Exception if HTTP status returned is > 299
        - Any exception raised by the SearchTransactionsApi call
        """  # noqa: D401

        api = SearchTransactionsApi(self.get_client_configuration())

        query_string = " OR ".join(
            [f"clientReferenceInformation.code:{s}" for s in reference_numbers]
        )

        query_request = CreateSearchRequest(
            save=False,
            name="MITOL",
            timezone=settings.TIME_ZONE,
            offset=0,
            limit=limit,
            sort="submitTimeUtc:desc",
            query=query_string,
        )

        response, status, _body = api.create_search(
            json.dumps(strip_nones(query_request.__dict__))
        )

        if status > 299:  # noqa: PLR2004
            raise Exception(  # noqa: TRY002, TRY003
                f"CyberSource API returned HTTP status {status}: {response!s}"  # noqa: EM102
            )

        if response.total_count == 0:
            return []

        return [
            [
                summary.id,
                summary.client_reference_information.code,
                summary.submit_time_utc,
            ]
            for summary in response._embedded.transaction_summaries  # noqa: SLF001
        ]

    def get_transaction_details(self, transaction: str):
        """
        Gets the details for a particular transaction. The details will be
        reformmated into a format resembling a CyberSource payload. This expects
        a CyberSource transaction ID, not an app-specific ID; the
        find_transactions method can be used to retrieve that if you don't have
        the transaction ID.

        Args:
        - transaction: CyberSource transaction ID to retrieve

        Returns:
        - Tuple of TssV2TransactionsGet200Response and a CyberSource-specific transaction object

        Raises:
        - Exception if HTTP status returned is > 299
        - Any exception raised by the TransactionDetailsApi call
        """  # noqa: E501, D401

        api = TransactionDetailsApi(self.get_client_configuration())

        response, status, _body = api.get_transaction(transaction)

        if status > 299:  # noqa: PLR2004
            raise Exception(  # noqa: TRY002, TRY003
                f"CyberSource API returned HTTP status {status}: {response!s}"  # noqa: EM102
            )

        payload = {
            "utf8": "",
            "message": response.application_information.applications[-1].r_message,
            "decision": response.application_information.applications[-1].reason_code,
            "auth_code": response.processor_information.approval_code,
            "auth_time": response.submit_time_utc,
            "signature": "",
            "req_amount": response.order_information.amount_details.total_amount,
            "req_locale": "en-us",
            "auth_amount": response.order_information.amount_details.authorized_amount,
            "reason_code": response.application_information.applications[
                -1
            ].reason_code,
            "req_currency": response.order_information.amount_details.currency,
            "auth_avs_code": response.processor_information.avs.code,
            "auth_response": response.processor_information.response_code,
            "req_card_type": "",
            "request_token": "",
            "card_type_name": "",
            "req_access_key": "",
            "req_profile_id": settings.MITOL_PAYMENT_GATEWAY_CYBERSOURCE_PROFILE_ID,
            "transaction_id": response.root_id,
            "req_card_number": "",
            "req_consumer_id": response.buyer_information.merchant_customer_id,
            "req_line_item_count": len(response.order_information.line_items),
            "signed_date_time": response.submit_time_utc,
            "auth_avs_code_raw": response.processor_information.avs.code_raw,
            "auth_trans_ref_no": response.processor_information.network_transaction_id,
            "bill_trans_ref_no": response.processor_information.network_transaction_id,
            "req_payment_method": "card",
            "req_card_expiry_date": f"{response.payment_information.card.expiration_month}-{response.payment_information.card.expiration_year}",  # noqa: E501
            "req_transaction_type": "sale",
            "req_transaction_uuid": "",
            "req_customer_ip_address": response.device_information.ip_address,
            "signed_field_names": "",
            "req_bill_to_email": response.order_information.bill_to.email,
            "req_bill_to_surname": response.order_information.bill_to.last_name,
            "req_bill_to_forename": response.order_information.bill_to.first_name,
            "req_bill_to_address_city": response.order_information.bill_to.locality,
            "req_bill_to_address_line1": response.order_information.bill_to.address1,
            "req_bill_to_address_state": response.order_information.bill_to.administrative_area,  # noqa: E501
            "req_bill_to_address_country": response.order_information.bill_to.country,
            "req_bill_to_address_postal_code": response.order_information.bill_to.postal_code,  # noqa: E501
            "req_override_custom_cancel_page": "https://rc.mitxonline.mit.edu/checkout/result/",
            "req_override_custom_receipt_page": "https://rc.mitxonline.mit.edu/checkout/result/",
            "req_card_type_selection_indicator": response.payment_information.card.type,
            "req_reference_number": response.client_reference_information.code,
        }

        for idx, line_item in enumerate(response.order_information.line_items):
            payload = {
                **payload,
                f"req_item_{idx}_quantity": line_item.quantity,
                f"req_item_{idx}_code": line_item.product_code,
                f"req_item_{idx}_name": line_item.product_name,
                f"req_item_{idx}_tax_amount": line_item.tax_amount,
                f"req_item_{idx}_unit_price": line_item.unit_price,
                f"req_item_{idx}_sku": line_item.product_sku,
            }

        for merchant_info in response.merchant_defined_information:
            payload = {
                **payload,
                f"req_merchant_defined_data{merchant_info.key}": merchant_info.value,
            }

        return (response, payload)

    def find_and_get_transactions(self, reference_numbers: list[str]):
        """
        For the reference numbers specified, gets the transaction details and
        returns that. In the case that there are multiple results for the
        reference number, the *last* one will be the one it uses.

        Args:
        - reference_numbers (list of str): app-specific reference numbers to search for

        Returns:
        - Dict of formatted responses. The keys will be the reference numbers.
        """

        limit = len(reference_numbers) if len(reference_numbers) > 20 else 20  # noqa: PLR2004
        results = {}

        searches = self.find_transactions(reference_numbers, limit)

        for search in searches:
            results[search[1]] = search[0]

        for order_id in results.items():
            search_id = results[order_id]

            (_orig_response, formatted_response) = self.get_transaction_details(
                search_id
            )

            results[order_id] = formatted_response

        return results


class StripePaymentGateway(
    PaymentGateway, gateway_class=constants.MITOL_PAYMENT_GATEWAY_STRIPE
):
    """
    The implementation of PaymentGateway for Stripe.

    Relevant documentation: https://docs.stripe.com/api
    """

    stripe_client: stripe.StripeClient | None = None

    @staticmethod
    def get_client_configuration():
        """
        Get the Stripe client config.
        """
        configuration_dictionary = {
            "api_key": settings.MITOL_PAYMENT_GATEWAY_STRIPE_API_KEY,
        }
        return configuration_dictionary  # noqa: RET504

    def __init__(self):
        """Initialize the gateway and bring up a Stripe client."""

        config = StripePaymentGateway.get_client_configuration()
        api_key = config.get("api_key", None)
        if not api_key:
            msg = "Stripe API key not set"
            raise ImproperlyConfigured(msg)
        self.stripe_client = stripe.StripeClient(api_key)

    def _get_stripe_checkout_session_v1(self):
        """Return the checkout session v1 client (mostly to make testing easier)."""

        return self.stripe_client.v1.checkout.sessions

    def _generate_product_data(self, item: CartItem | LookupCartItem):
        """
        Generate the Stripe product data for the line.

        The shape of the data changes if the product is defined in-line or not.
        """

        if isinstance(item, LookupCartItem):
            return {"product": item.product_id}
        elif isinstance(item, CartItem):
            return {
                "product_data": {
                    "name": item.name,
                    "description": item.name,
                    "metadata": asdict(item),
                }
            }

        raise ImproperCartItemError(item)

    def _generate_price_data(self, item: CartItem | LookupCartItem):
        """
        Generate the price data for the item.

        This is always defined inline for this iteration. If a taxable amount is
        defined, then that amount is added to the unit price.

        Stripe is able to calculate taxes. However, we have been historically
        calculating this ourselves. So, this **always** sets the tax behavior to
        "inclusive" so that ti does not try to re-calculate the tax. This decision
        will need to be revisited if we opt to use Stripe's tax calculation
        functionality in the future.

        It's not entirely clear here from the docs but you actually have to pass
        the price in cents (for USD).
        """

        return {
            "price_data": {
                "currency": "USD",
                "unit_amount_decimal": (
                    Decimal(item.unitprice + item.taxable).quantize(Decimal("1.00"))
                    * 100
                ),
                "tax_behavior": "inclusive",
                **self._generate_product_data(item),
            }
        }

    def _generate_line_item(self, item: CartItem | LookupCartItem):
        """Generate a Stripe line item."""

        return {
            "quantity": item.quantity,
            **self._generate_price_data(item),
        }

    def _validate_event_payload(self, request):
        """Validate an event payload."""

        payload = request.body

        if len(payload) == 0:
            msg = "Empty payload received."
            raise ImproperStripeWebhookRequestError(msg)

        try:
            payload_json = json.loads(payload)
        except (json.JSONDecodeError, UnicodeDecodeError) as exc:
            msg = "Improper JSON payload found."
            raise ImproperStripeWebhookRequestError(msg) from exc

        if "id" not in payload_json:
            msg = "Improper JSON payload found (no 'id' prop)."
            raise ImproperStripeWebhookRequestError(msg)

        return payload_json["id"]

    def prepare_checkout(
        self,
        order: Order,
        receipt_url: str | None = None,
        cancel_url: str | None = None,
        backoffice_post_url: str | None = None,
        **kwargs,
    ):
        """
        Set up and return the Checkout Session.

        Checkout Session is Stripe's payment workflow. These are created via an
        API call, resulting in a Checkout Session object that includes a URL to
        send the user to.

        The full session object is returned in the "payload" key. The session
        object includes the ID for the session; this should be retained for
        future processing (e.g. on the success page), but the remaining data is
        not used by Payment Gateway.

        Stripe can inject the session ID into the receipt and cancel URLs. Also,
        the backoffice URL (webhook target URL) cannot be set here and will
        generate a warning message in the log if set. For more information, see
        README-Stripe.md.
        """

        if backoffice_post_url:
            log.warning(
                "prepare_checkout: custom backoffice URL set for Stripe "
                "transaction, ignoring"
            )

        merchant_fields = kwargs.get("merchant_fields", {})

        stripe_session_data = {
            "client_reference_id": order.reference,
            "customer_email": order.email,
            "line_items": [self._generate_line_item(item) for item in order.items],
            "mode": "payment",
            "ui_mode": "hosted_page",
            "success_url": receipt_url,
            "cancel_url": cancel_url,
            "metadata": merchant_fields if isinstance(merchant_fields, dict) else None,
        }

        response = self.stripe_client.v1.checkout.sessions.create(stripe_session_data)

        return {
            "payload": response,
            "url": response.url,
            "method": "GET",
        }

    @staticmethod
    def get_refund_request(transaction_dict: dict, *, amount: Decimal | None = None):
        """
        Set up a Refund object for processing through Stripe.

        Stripe wants the PaymentIntent from the completed transaction to set up
        a refund - this is included in the transaction data that should be stored
        after the transaction succeeds, so this will scrape that out of there for
        you. (Generally this will actually be an event payload, so this will
        also strip off the event wrapper.)

        You can optionally provide an amount to perform a partial refund.

        Args:
        - transaction_dict (dict): the stored Stripe transaction data
        Keyword Args:
        - amount (Decimal|None): amount to refund, if performing a partial refund
        """

        if transaction_dict.get("object") == "event":
            ev_data = transaction_dict.get("data")

            if not ev_data:
                msg = "Transaction data passed says it's an event, but has no data."
                raise InvalidStripeCheckoutSessionError(msg)

            checkout_session = ev_data.get("object")
        elif transaction_dict.get("object") == "checkout.session":
            checkout_session = transaction_dict
        else:
            msg = (
                "Transaction data passed either does not have an 'object' prop "
                "or is not one of the supported object types ('event' or "
                "'checkout.session')."
            )
            raise InvalidStripeCheckoutSessionError(msg)

        payment_intent = checkout_session.get("payment_intent")
        refund_obj = Refund(
            transaction_id="",
            refund_amount=(Decimal(checkout_session.get("amount_total", 0)) / 100),
            refund_currency=checkout_session.get("currency", ""),
        )

        if amount:
            refund_obj.refund_amount = amount

        if not payment_intent:
            raise InvalidStripeCheckoutSessionError

        # The PaymentIntent that gets sent back may either be a string identifier
        # or the full PaymentIntent object depending on whether or not expansion
        # was turned on at the time of retrieval.
        if isinstance(payment_intent, str):
            refund_obj.transaction_id = payment_intent
        else:
            refund_obj.transaction_id = payment_intent.get("id")

        return refund_obj

    def perform_processor_response_validation(self, request: HttpRequest):
        """
        Check for the signature header, and validate the signature against the store.

        Stripe signs webhook requests with a shared key. This key is specific to
        the configured webhook - there may be multiple valid keys configured for
        different webhooks, and there may be different configured webhooks for
        the same event type.

        The key store includes a mapping of urlconf routes to keys. This checks
        the provided signed signature against all of the applicable keys. If no
        keys are found (at all), then NoStripeWebhookSecretError is raised. If
        none of the keys are valid for the signature, then BadStripeWebhookSecretError
        is raised.

        If verification is successful, the event is returned.
        """

        payload = request.body
        event_id = self._validate_event_payload(request)

        signature_to_validate = request.headers.get("Stripe-Signature", False)
        if not signature_to_validate:
            raise ImproperStripeWebhookRequestError

        key_qs = StripeWebhookSecret.get_secret_from_request_queryset(request)
        if not key_qs.exists():
            raise NoStripeWebhookSecretError(event_id=event_id)

        found_valid_key = False

        for key in key_qs.all():
            try:
                event = self.stripe_client.construct_event(
                    payload,
                    signature_to_validate,
                    key.webhook_secret,
                )
                found_valid_key = True
                break
            except ValueError as exc:
                raise ImproperStripeWebhookRequestError from exc
            except stripe.SignatureVerificationError:
                # We expect this one - if there's >1 key, then only one will be valid.
                pass

        if not found_valid_key:
            raise BadStripeWebhookSecretError(event_id=event_id)

        return event

    def decode_processor_response(self, request: HttpRequest):
        """
        Decode the response from Stripe.

        The validation returns the event; the event object contains the data
        associated with the event, so this strips the event parts out and returns
        just the data. The data returned will depend on the event that was triggered.
        """

        return self.perform_processor_response_validation(request).data.object

    def perform_refund(
        self,
        refund: Refund,
        *,
        refund_reason: str = constants.STRIPE_REFUND_REASON_CUSTOMER_REQUEST,
    ):
        """
        Submit the refund request through Stripe.

        Relevant API docs: https://docs.stripe.com/api/refunds

        The Stripe refund API doesn't allow for specifying the refund currency.
        It will use whatever currency is specified in the related PaymentIntent
        object. If you need to do a partial refund, ensure the amount specified
        is in *that* currency. (This is potentially *not* USD!)

        Be careful setting refund_reason - "requested_by_customer" is the default
        and should apply in almost all cases. Setting the reason to "fraudulent"
        will block the card and may trigger some other fraud prevention-related
        actions within Stripe.

        An exception will be raised by the Stripe client if an API error occurs;
        if there's simply a problem with the refund, this will not raise (unlike
        the CyberSource implementation). Refund errors may require some additional
        manual work so returning the payload makes more sense. Do not assume that
        a response means the refund request was successful.

        Args:
        - refund (Refund): the Refund request, generated by get_refund_request
        Keyword Args:
        - refund_reason (str): the reason for the refund
          (default to requested_by_customer)
        """

        if refund_reason not in constants.STRIPE_REFUND_REASONS:
            msg = f"Invalid refund reason {refund_reason}"
            raise ValueError(msg)

        stripe_refund = stripe.params.RefundCreateParams(
            payment_intent=refund.transaction_id,
            amount=int(Decimal(refund.refund_amount * 100).quantize(Decimal("1"))),
            reason=refund_reason,
        )

        return self.stripe_client.v1.refunds.create(stripe_refund)

    def filter_event(
        self,
        event: stripe.Event,
        valid_events: list[str] = constants.STRIPE_EVENTS_CHECKOUT_SESSION,
    ) -> object | None:
        """
        Check the event against a list of acceptable types and return the object.

        Stripe has lots of event types that are all potentially reported through
        a single webhook interface. A given bit of logic probably only cares about
        a couple of types, though, so this filters the object according to the
        supplied types. If it passes, you get the data object you were expecting;
        if not, you get None and can quit out. This should happen after
        perform_processor_response_validation.

        Default event types are the checkout session ones since that's the most
        relevant to current ecommerce implementations.
        """

        return event.data.object if event.type in valid_events else None

    def _calculate_checkout_session_status(
        self, cs: StripeCheckoutSession, session_status: StripeCheckoutSessionStatus
    ):
        """Calculate status using only the checkout session status fields."""

        if cs.status == constants.STRIPE_CHECKOUT_SESSION_STATUS_OPEN or (
            cs.status == constants.STRIPE_CHECKOUT_SESSION_STATUS_COMPLETE
            and cs.payment_status == constants.STRIPE_PAYMENT_STATUS_UNPAID
        ):
            session_status.status = constants.STRIPE_OVERALL_CHECKOUT_STATUS_PENDING
        elif cs.status == constants.STRIPE_CHECKOUT_SESSION_STATUS_COMPLETE and (
            cs.payment_status in constants.STRIPE_PAYMENT_STATUSES_GOOD
        ):
            # "complete" and "paid" is a weird state here
            # - we should have a PaymentIntent to check
            session_status.status = constants.STRIPE_OVERALL_CHECKOUT_STATUS_PAID
        elif (
            cs.status == "expired"
            and cs.payment_status == constants.STRIPE_PAYMENT_STATUS_UNPAID
        ):
            session_status.status = constants.STRIPE_OVERALL_CHECKOUT_STATUS_CANCELLED
            session_status.cancel_reason = "expired-unpaid"
        else:
            # weird state again - expired and paid or expired and no-payment-required

            log.warning(
                "Checkout session %s in weird state: state %s and payment_state %s",
                cs.id,
                cs.status,
                cs.payment_status,
            )
            session_status.status = constants.STRIPE_OVERALL_CHECKOUT_STATUS_PENDING

        return session_status

    def calculate_checkout_session_status(
        self, checkout_session: dict | str | StripeCheckoutSession
    ) -> StripeCheckoutSessionStatus:
        """
        Process the provided Stripe CheckoutSession and provide its status.

        The status of a Checkout Session requires calculation. The CheckoutSession
        itself has two status fields, and (if it exists) its PaymentIntent has
        another field that describes the state of the payment process. So, this
        calculates the overall status using all these fields.

        If a checkout session object is passed in, this will generate a new API
        request for the checkout session details. This is both for ensuring that
        the data being processed is fresh and to ensure that any Payment Intents
        that may exist for the session are also loaded.

        Args:
        - checkout_session (dict|str|stripe.checkout.Session): a checkout session,
          or the ID for one
        Returns:
        - StripeCheckoutSessionStatus; the overall status of the session
        """

        stripe_checkout_session_client = self._get_stripe_checkout_session_v1()

        if isinstance(checkout_session, dict):
            session_id = checkout_session.get("id")
        elif isinstance(checkout_session, StripeCheckoutSession):
            session_id = checkout_session.id
        else:
            session_id = checkout_session

        if not session_id:
            msg = "checkout session ID not found"
            raise ValueError(msg)

        # Call this directly so we can tell the client to expand payment_intent.

        fetched_checkout_session = stripe_checkout_session_client.retrieve(
            session_id,
            {
                "expand": [
                    "payment_intent",
                ],
            },
        )

        # The session itself has two status fields: status and payment_status
        # status is the session status - open, complete, expired
        # payment_status is payment with relation to the session - no_payment_required,
        # paid, unpaid
        # The PaymentIntent (if it exists) has the status of whatever actual payment
        # was received. If cancelled, it also has a cancellation reason.

        session_status = StripeCheckoutSessionStatus(
            status=constants.STRIPE_OVERALL_CHECKOUT_STATUS_PENDING,
            checkout_session_id=fetched_checkout_session.id,
            transaction=fetched_checkout_session.to_dict(for_json=True),
            payment_intent_id=None,
            cancel_reason=None,
            action_reason=None,
        )

        if not fetched_checkout_session.payment_intent:
            # No payment intent at all, so just use the session statuses.
            return self._calculate_checkout_session_status(
                fetched_checkout_session, session_status
            )

        if not isinstance(
            fetched_checkout_session.payment_intent, stripe.PaymentIntent
        ):
            msg = "Payment intent is of incorrect type."
            raise TypeError(msg)

        pi = fetched_checkout_session.payment_intent
        session_status.payment_intent_id = pi.id

        if pi.status == constants.STRIPE_PAYMENT_INTENT_STATUS_PROCESSING:
            session_status.status = constants.STRIPE_OVERALL_CHECKOUT_STATUS_PENDING
        elif pi.status == constants.STRIPE_PAYMENT_INTENT_STATUS_SUCCEEDED:
            session_status.status = constants.STRIPE_OVERALL_CHECKOUT_STATUS_PAID
        elif pi.status == constants.STRIPE_PAYMENT_INTENT_STATUS_CANCELLED:
            session_status.status = constants.STRIPE_OVERALL_CHECKOUT_STATUS_CANCELLED
            session_status.cancel_reason = pi.cancellation_reason
        else:
            session_status.status = (
                constants.STRIPE_OVERALL_CHECKOUT_STATUS_PENDING_ACTION
            )
            session_status.action_reason = pi.status

        return session_status
