"""Constants for the Payment Gateway."""

ISO_8601_FORMAT = "%Y-%m-%dT%H:%M:%SZ"

MITOL_PAYMENT_GATEWAY_NONE = "None"
MITOL_PAYMENT_GATEWAY_CYBERSOURCE = "CyberSource"
MITOL_PAYMENT_GATEWAY_STRIPE = "Stripe"

CART_ITEM_INLINE = "inline"
CART_ITEM_DEFINED = "defined"
CART_ITEM_UNKNOWN = "unknown"

# Actions for the NonePaymentGateway to take.
MITOL_PAYMENT_GATEWAY_NONE_ACTION_DENY = "deny"
MITOL_PAYMENT_GATEWAY_NONE_ACTION_APPROVE = "approve"
MITOL_PAYMENT_GATEWAY_NONE_ACTION_APPROVE_ZERO = "approve-zero"

CYBERSOURCE_DECISION_ACCEPT = "ACCEPT"
CYBERSOURCE_DECISION_DECLINE = "DECLINE"
CYBERSOURCE_DECISION_REVIEW = "REVIEW"
CYBERSOURCE_DECISION_ERROR = "ERROR"
CYBERSOURCE_DECISION_CANCEL = "CANCEL"

CYBERSOURCE_CARD_TYPES = {
    "001": "Visa",
    "002": "Mastercard",
    "003": "American Express",
    "004": "Discover",
    "005": "Diners Club",
    "006": "Carte Blanche",
    "007": "JCB",
    "014": "Enroute",
    "021": "JAL",
    "024": "Maestro (UK)",
    "031": "Delta",
    "033": "Visa Electron",
    "034": "Dankort",
    "036": "Carte Bancaires",
    "037": "Carta Si",
    "039": "EAN",
    "040": "UATP",
    "042": "Maestro (Intl)",
    "050": "Hipercard",
    "051": "Aura",
    "054": "Elo",
    "061": "RuPay",
    "062": "China UnionPay",
}

STRIPE_OBJECT_CHECKOUT_SESSION = "checkout.session"

STRIPE_EVENT_CHECKOUT_SESSION_COMPLETED = "checkout.session.completed"
STRIPE_EVENT_CHECKOUT_SESSION_EXPIRED = "checkout.session.expired"
STRIPE_EVENT_CHECKOUT_SESSION_ASYNC_PAYMENT_FAILED = (
    "checkout.session.async_payment_failed"
)
STRIPE_EVENT_CHECKOUT_SESSION_ASYNC_PAYMENT_SUCCEEDED = (
    "checkout.session.async_payment_succeeded"
)

STRIPE_EVENTS_CHECKOUT_SESSION = [
    STRIPE_EVENT_CHECKOUT_SESSION_COMPLETED,
    STRIPE_EVENT_CHECKOUT_SESSION_EXPIRED,
    STRIPE_EVENT_CHECKOUT_SESSION_ASYNC_PAYMENT_FAILED,
    STRIPE_EVENT_CHECKOUT_SESSION_ASYNC_PAYMENT_SUCCEEDED,
]

STRIPE_PAYMENT_STATUS_PAID = "paid"
STRIPE_PAYMENT_STATUS_NPR = "no_payment_required"
STRIPE_PAYMENT_STATUS_UNPAID = "unpaid"

STRIPE_CHECKOUT_SESSION_STATUS_COMPLETE = "complete"
STRIPE_CHECKOUT_SESSION_STATUS_EXPIRED = "expired"
STRIPE_CHECKOUT_SESSION_STATUS_OPEN = "open"

STRIPE_PAYMENT_INTENT_STATUS_PROCESSING = "processing"
STRIPE_PAYMENT_INTENT_STATUS_SUCCEEDED = "succeeded"
STRIPE_PAYMENT_INTENT_STATUS_CANCELLED = "cancelled"
STRIPE_PAYMENT_INTENT_STATUS_REQUIRES_ACTION = "requires_action"
STRIPE_PAYMENT_INTENT_STATUS_REQUIRES_CAPTURE = "requires_capture"
STRIPE_PAYMENT_INTENT_STATUS_REQUIRES_CONFIRMATION = "requires_confirmation"
STRIPE_PAYMENT_INTENT_STATUS_REQUIRES_PAYMENT_METHOD = "requires_payment_method"

STRIPE_PAYMENT_STATUSES_GOOD = [
    STRIPE_PAYMENT_STATUS_NPR,
    STRIPE_PAYMENT_STATUS_PAID,
]
STRIPE_PAYMENT_INTENT_STATUSES_COMPLETE = [
    STRIPE_PAYMENT_INTENT_STATUS_SUCCEEDED,
    STRIPE_PAYMENT_INTENT_STATUS_CANCELLED,
]
STRIPE_PAYMENT_INTENT_STATUSES_PENDING = [
    STRIPE_PAYMENT_INTENT_STATUS_PROCESSING,
    STRIPE_PAYMENT_INTENT_STATUS_REQUIRES_ACTION,
    STRIPE_PAYMENT_INTENT_STATUS_REQUIRES_CAPTURE,
    STRIPE_PAYMENT_INTENT_STATUS_REQUIRES_CONFIRMATION,
    STRIPE_PAYMENT_INTENT_STATUS_REQUIRES_PAYMENT_METHOD,
]

STRIPE_REFUND_REASON_DUPLICATE = "duplicate"
STRIPE_REFUND_REASON_FRAUD = "fradulent"
STRIPE_REFUND_REASON_CUSTOMER_REQUEST = "requested_by_customer"
STRIPE_REFUND_REASONS = [
    STRIPE_REFUND_REASON_DUPLICATE,
    STRIPE_REFUND_REASON_FRAUD,
    STRIPE_REFUND_REASON_CUSTOMER_REQUEST,
]

STRIPE_OVERALL_CHECKOUT_STATUS_PENDING = "pending"
STRIPE_OVERALL_CHECKOUT_STATUS_PENDING_ACTION = "pending-action"
STRIPE_OVERALL_CHECKOUT_STATUS_PAID = "paid"
STRIPE_OVERALL_CHECKOUT_STATUS_CANCELLED = "cancelled"
STRIPE_OVERALL_CHECKOUT_STATUS_ERROR = "error"
