[project]
name = "mitol-django-google-sheets"
version = "2022.6.22"

[tool.bumpver]
current_version = "2022.6.22"
version_pattern = "YYYY.MM.DD[.INC0]"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"__init__.py" = [
    '__version__ = "{version}"',
]