# Generated by Django 4.2.16 on 2024-11-04 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geoip", "0001_add_geoip_tables"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="netblock",
            new_name="geoip_netbl_decimal_d4f6be_idx",
            old_name="maxmind_net_decimal_dfdb1a_idx",
        ),
        migrations.RenameIndex(
            model_name="netblock",
            new_name="geoip_netbl_decimal_29d863_idx",
            old_name="maxmind_net_decimal_6166c4_idx",
        ),
        migrations.RenameIndex(
            model_name="netblock",
            new_name="geoip_netbl_decimal_724563_idx",
            old_name="maxmind_net_decimal_ab7249_idx",
        ),
    ]
