# Generated by Django 2.2.17 on 2020-12-08 19:46  # noqa: D100

from django.db import migrations


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [  # noqa: RUF012
        ("digitalcredentials", "0001_add_digital_credentials_models"),
    ]

    operations = [  # noqa: RUF012
        migrations.RenameField(
            model_name="digitalcredential",
            old_name="courseware_content_type",
            new_name="credentialed_content_type",
        ),
        migrations.RenameField(
            model_name="digitalcredential",
            old_name="courseware_object_id",
            new_name="credentialed_object_id",
        ),
        migrations.RenameField(
            model_name="digitalcredentialrequest",
            old_name="courseware_content_type",
            new_name="credentialed_content_type",
        ),
        migrations.RenameField(
            model_name="digitalcredentialrequest",
            old_name="courseware_object_id",
            new_name="credentialed_object_id",
        ),
    ]
