[tool.poetry]
name = "mitol-django-authentication"
version = "0.1.0"
description = "MIT Open Learning django app extensions for social-auth"
authors = [
  "MIT Office of Open Learning <mitx-devops@mit.edu>"
]
keywords = [
]
classifiers = [
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8"
]
packages = [
    { include = "mitol" },
]
include = [
  "LICENSE"
]

[tool.poetry.dependencies]
python = "~3.6 | ~3.7 | ~3.8"
Django = "^2.2.12"
djangorestframework = "^3.0.0"
social-auth-app-django = "^3.1.0"
social-auth-core = "^3.3.3"
mitol-django-common = "^0.6.0"
mitol-django-mail = "^0.4.0"
python3-saml = "^1.10.1"

# Testers
pytest = {version = "^4.6", optional = true}
pytest-cov = {version = "*", optional = true}
pytest-mock = {version = "1.10.1", optional = true}
pytest-django = {version = "3.4.8", optional = true}
codecov = {version = "*", optional = true}

# Formatters
isort = {version = "^4.3.21", optional = true}
black = {version = "^19.10b0", optional = true}

# Linters
pylint = {version = "^2.0", optional = true}
pylint-django = {version = "^2.0.2", optional = true}

# Misc
ipython = {version = "^7.13.0", optional = true}
factory_boy = {version = "^2.12.0", optional = true}
responses = {version = "^0.10.14", optional = true}

[tool.isort]
not_skip = "__init__.py"

multi_line_output = 3

known_standard_library = "dataclasses,typing_extensions"
known_first_party = ["mitol"]

combine_as_imports = true
force_grid_wrap = false
include_trailing_comma = true

lines_after_imports = 2
line_length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
