# Generated by Django 3.2.13 on 2022-06-02 17:47  # noqa: D100

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [  # noqa: RUF012
        ("testapp", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="AuditableTestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
