target(
    name="mitol-sources",
    dependencies=[
        f"//src/mitol/{name}"
        for name in [
            "authentication",
            "common",
            "digitalcredentials",
            "google_sheets",
            "google_sheets_refunds",
            "hubspot_api",
            "mail",
            "oauth_toolkit_extensions",
            "openedx",
            "payment_gateway",
        ]
    ],
)
