---
name: Renovate
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'
permissions:
  pull-requests: write
  contents: write
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Apt install
      run: sudo apt-get update && sudo apt-get install -y libxmlsec1-dev

    - name: Install uv
      uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@973d3e5a68e735a444e8c03432b66eedb343c302 # v46.2.0
      with:
        configurationFile: renovate-config.json
        token: ${{ secrets.GITHUB_TOKEN }}
